"""empty message

Revision ID: 133eb8761b89
Revises: 97fc0c85196c
Create Date: 2019-07-07 00:55:03.248768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '133eb8761b89'
down_revision = '97fc0c85196c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('spouseLastname', sa.String(length=120), nullable=True))
    op.drop_column('forms', 'souseLastname')
    op.add_column('spouse', sa.Column('spouseLastname', sa.String(length=120), nullable=True))
    op.drop_column('spouse', 'souseLastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spouse', sa.Column('souseLastname', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('spouse', 'spouseLastname')
    op.add_column('forms', sa.Column('souseLastname', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('forms', 'spouseLastname')
    # ### end Alembic commands ###
