"""empty message

Revision ID: 2edd0d27b743
Revises: b15cada9eb6e
Create Date: 2019-06-26 17:58:30.196296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2edd0d27b743'
down_revision = 'b15cada9eb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('logged_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'logged_in')
    # ### end Alembic commands ###
