"""empty message

Revision ID: 49beb0d0306c
Revises: 3d406abab95d
Create Date: 2019-08-03 04:20:02.077263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49beb0d0306c'
down_revision = '3d406abab95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('address1', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('apartment1', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('city1', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('country1', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('firstname1', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('lastname1', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('middlename1', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('state1', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('zipCode1', sa.String(length=120), nullable=True))
    op.add_column('person', sa.Column('address1', sa.String(length=120), nullable=True))
    op.add_column('person', sa.Column('apartment1', sa.String(length=120), nullable=True))
    op.add_column('person', sa.Column('city1', sa.String(length=120), nullable=True))
    op.add_column('person', sa.Column('country1', sa.String(length=120), nullable=True))
    op.add_column('person', sa.Column('firstname1', sa.String(length=120), nullable=True))
    op.add_column('person', sa.Column('lastname1', sa.String(length=120), nullable=True))
    op.add_column('person', sa.Column('middlename1', sa.String(length=120), nullable=True))
    op.add_column('person', sa.Column('state1', sa.String(length=120), nullable=True))
    op.add_column('person', sa.Column('zipCode1', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'zipCode1')
    op.drop_column('person', 'state1')
    op.drop_column('person', 'middlename1')
    op.drop_column('person', 'lastname1')
    op.drop_column('person', 'firstname1')
    op.drop_column('person', 'country1')
    op.drop_column('person', 'city1')
    op.drop_column('person', 'apartment1')
    op.drop_column('person', 'address1')
    op.drop_column('forms', 'zipCode1')
    op.drop_column('forms', 'state1')
    op.drop_column('forms', 'middlename1')
    op.drop_column('forms', 'lastname1')
    op.drop_column('forms', 'firstname1')
    op.drop_column('forms', 'country1')
    op.drop_column('forms', 'city1')
    op.drop_column('forms', 'apartment1')
    op.drop_column('forms', 'address1')
    # ### end Alembic commands ###
