"""empty message

Revision ID: 54379b61438e
Revises: 
Create Date: 2019-06-20 19:10:03.417097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54379b61438e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.String(length=80), nullable=False),
    sa.Column('application_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id'),
    sa.UniqueConstraint('application_name')
    )
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forms_id', sa.String(length=120), nullable=False),
    sa.Column('forms_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forms_id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('firstname', sa.String(length=120), nullable=True),
    sa.Column('middlename', sa.String(length=120), nullable=True),
    sa.Column('sex', sa.String(length=6), nullable=True),
    sa.Column('dateOfBirth', sa.Date(), nullable=True),
    sa.Column('countryOfBirth', sa.String(length=30), nullable=True),
    sa.Column('citizenship', sa.String(length=30), nullable=True),
    sa.Column('US_Address', sa.String(length=120), nullable=True),
    sa.Column('apartment', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('spouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('firstname', sa.String(length=120), nullable=True),
    sa.Column('middlename', sa.String(length=120), nullable=True),
    sa.Column('sex', sa.String(length=6), nullable=True),
    sa.Column('dateOfBirth', sa.Date(), nullable=True),
    sa.Column('countryOfBirth', sa.String(length=30), nullable=True),
    sa.Column('citizenship', sa.String(length=30), nullable=True),
    sa.Column('US_Address', sa.String(length=120), nullable=True),
    sa.Column('apartment', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('spouse_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('spouse_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spouse')
    op.drop_table('person')
    op.drop_table('forms')
    op.drop_table('application')
    # ### end Alembic commands ###
