"""empty message

Revision ID: 5916f3ee4c79
Revises: 0b389171edec
Create Date: 2019-06-27 16:53:29.890361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5916f3ee4c79'
down_revision = '0b389171edec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('apartment', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('country', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('dayPhone', sa.String(length=12), nullable=True))
    op.add_column('forms', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('firstname', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('lastname', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('logged_in', sa.Boolean(), nullable=True))
    op.add_column('forms', sa.Column('middlename', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('forms', sa.Column('state', sa.String(length=120), nullable=True))
    op.add_column('forms', sa.Column('zip_code', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'zip_code')
    op.drop_column('forms', 'state')
    op.drop_column('forms', 'mobile')
    op.drop_column('forms', 'middlename')
    op.drop_column('forms', 'logged_in')
    op.drop_column('forms', 'lastname')
    op.drop_column('forms', 'firstname')
    op.drop_column('forms', 'email')
    op.drop_column('forms', 'dayPhone')
    op.drop_column('forms', 'country')
    op.drop_column('forms', 'city')
    op.drop_column('forms', 'apartment')
    op.drop_column('forms', 'address')
    # ### end Alembic commands ###
