"""empty message

Revision ID: b15cada9eb6e
Revises: 2399fb9c7c39
Create Date: 2019-06-23 23:41:45.654506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b15cada9eb6e'
down_revision = '2399fb9c7c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('dayPhone', sa.String(length=12), nullable=True))
    op.drop_column('person', 'zip')
    op.drop_column('person', 'dateOfBirth')
    op.drop_column('person', 'sex')
    op.drop_column('person', 'city')
    op.drop_column('person', 'US_Address')
    op.drop_column('person', 'countryOfBirth')
    op.drop_column('person', 'citizenship')
    op.drop_column('person', 'state')
    op.drop_column('person', 'apartment')
    op.add_column('spouse', sa.Column('dayPhone', sa.String(length=20), nullable=True))
    op.drop_column('spouse', 'zip')
    op.drop_column('spouse', 'dateOfBirth')
    op.drop_column('spouse', 'sex')
    op.drop_column('spouse', 'city')
    op.drop_column('spouse', 'US_Address')
    op.drop_column('spouse', 'countryOfBirth')
    op.drop_column('spouse', 'citizenship')
    op.drop_column('spouse', 'state')
    op.drop_column('spouse', 'apartment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spouse', sa.Column('apartment', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('spouse', sa.Column('state', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('spouse', sa.Column('citizenship', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('spouse', sa.Column('countryOfBirth', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('spouse', sa.Column('US_Address', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('spouse', sa.Column('city', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('spouse', sa.Column('sex', mysql.VARCHAR(length=6), nullable=True))
    op.add_column('spouse', sa.Column('dateOfBirth', sa.DATE(), nullable=True))
    op.add_column('spouse', sa.Column('zip', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('spouse', 'dayPhone')
    op.add_column('person', sa.Column('apartment', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('person', sa.Column('state', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('person', sa.Column('citizenship', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('person', sa.Column('countryOfBirth', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('person', sa.Column('US_Address', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('person', sa.Column('city', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('person', sa.Column('sex', mysql.VARCHAR(length=6), nullable=True))
    op.add_column('person', sa.Column('dateOfBirth', sa.DATE(), nullable=True))
    op.add_column('person', sa.Column('zip', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('person', 'dayPhone')
    # ### end Alembic commands ###
