"""empty message

Revision ID: b5baf422715d
Revises: 2edd0d27b743
Create Date: 2019-06-26 18:04:06.739212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5baf422715d'
down_revision = '2edd0d27b743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'is_completed')
    # ### end Alembic commands ###
